****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
Z_KURUMSAL_CALISAN_LISTESI																																
0100																																
752																																
             40																																
%_HEADER																																
Z_KURUMSAL_CALISAN_LISTESI              0100 0100     20 92192 37  0  0 29182  0G E                              20240930133020																																
%_DESCRIPTION																																
Çal##an Kay#t																																
%_FIELDS																																
CALISAN_EKLE		CHAR	 91	00	00	00	30	00	  2	  3		  0	  0	  0		 19	R				  0	  0	101							Çal##an_Kay#t_Ekran#______________________________________________________________________		
ID	0	CHAR	 20	00	00	00	30	00	  3	  5		  0	  0	  0		  0					  0	  0								ID__________________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  3	 26		  0	  0	  0		  0					  0	  0								:		
GV_ID	I	INT4	 10	80	00	80	02	00	  3	 28		  0	  0	  0		  0					  0	  0								__________		
GERI		CHAR	 11	00	00	00	30	00	  3	 79		  0	  0	  0		  9	P				  0	  0	102							@9S@_Geri__	                                                                                                                                                                        &BACK	
AD	0	CHAR	 20	00	00	00	30	00	  4	  5		  0	  0	  0		  0					  0	  0								Ad__________________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  4	 26		  0	  0	  0		  0					  0	  0								:		
GV_AD	C	CHAR	 20	80	00	80	02	00	  4	 28		  0	  0	  0		  0					  0	  0								____________________		
SOYAD	0	CHAR	 20	00	00	00	30	00	  5	  5		  0	  0	  0		  0					  0	  0								Soyad_______________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  5	 26		  0	  0	  0		  0					  0	  0								:		
GV_SOYAD	C	CHAR	 20	80	00	80	02	00	  5	 28		  0	  0	  0		  0					  0	  0								____________________		
CINSIYET	0	CHAR	 20	00	00	00	30	00	  6	  5		  0	  0	  0		  0					  0	  0								Cinsiyet____________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  6	 26		  0	  0	  0		  0					  0	  0								:		
GV_RAD1	C	CHAR	  1	80	00	80	00	00	  6	 28		  0	  0	  0		  0	A				  0	  0	103									
GV_RAD1	0	CHAR	  5	00	00	00	30	00	  6	 30		  0	  0	  0		  0	A				  0	  0	103							Erkek		
GV_RAD2	C	CHAR	  1	80	00	80	00	00	  6	 38		  0	  0	  0		  0	A				  0	  0	103									
GV_RAD2	0	CHAR	  5	00	00	00	30	00	  6	 40		  0	  0	  0		  0	A				  0	  0	103							Kad#n		
DOGUM	0	CHAR	 20	00	00	00	30	00	  7	  5		  0	  0	  0		  0					  0	  0								Do#um_Tarihi________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  7	 26		  0	  0	  0		  0					  0	  0								:		
GV_DOGUM	D	DATS	 10	80	00	80	02	08	  7	 28		  0	  0	  0		  0					  0	  0			SRM_F4_DATUM					__________		
YAS	0	CHAR	  3	00	00	00	30	00	  8	  5		  0	  0	  0		  0					  0	  0								Ya#	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  8	 26		  0	  0	  0		  0					  0	  0								:		
GV_YAS	I	INT4	 11	80	00	80	00	00	  8	 28		  0	  0	  0		 13					  0	  0								___________	 DL	
SEHIR	0	CHAR	 20	00	00	00	30	00	  9	  5		  0	  0	  0		  0					  0	  0								#ehir_______________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  9	 26		  0	  0	  0		  0					  0	  0								:		
GV_SEHIR	C	CHAR	 15	80	00	80	02	00	  9	 28		  0	  0	  0		  0					  0	  0								_______________		
TELEFON	0	CHAR	 20	00	00	00	30	00	 10	  5		  0	  0	  0		  0					  0	  0								Telefon_Numaras#____	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	 10	 26		  0	  0	  0		  0					  0	  0								:		
GV_TELEFON	C	CHAR	 20	80	00	80	02	00	 10	 28		  0	  0	  0		  0					  0	  0								____________________		
MAIL	0	CHAR	 20	00	00	00	30	00	 11	  5		  0	  0	  0		  0					  0	  0								Mail_Adresi_________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	 11	 26		  0	  0	  0		  0					  0	  0								:		
GV_MAIL	C	CHAR	 50	80	00	80	02	00	 11	 28		  0	  0	  0		  0					  0	  0								__________________________________________________		
TEMIZLE		CHAR	 24	00	00	00	30	00	 13	 24		  0	  0	  0		 15	P				  0	  0	104							@0Y@_Temizle____________	                                                                                                                                                                        &CLEAR	
KAYIT		CHAR	 17	00	00	00	30	00	 13	 50		  0	  0	  0		 15	P				  0	  0	105							@2L@_Kaydet______	                                                                                                                                                                        &SAVE	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_0100.																																
																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_0100.																																
%_PARAMS																																
																																
