****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
Z_KURUMSAL_CALISAN_LISTESI																																
0200																																
752																																
             40																																
%_HEADER																																
Z_KURUMSAL_CALISAN_LISTESI              0200 0200     21 94192 37  0  0 26118  0G E                              20241001084807																																
%_DESCRIPTION																																
Çal##an Bilgileri Güncelleme																																
%_FIELDS																																
CALISAN_GUNCELLE		CHAR	 91	00	00	00	30	00	  3	  5		  0	  0	  0		 19	R				  0	  0	101							Çal##an_Bilgi_Güncelleme__________________________________________________________________		
ID	0	CHAR	 20	00	00	00	30	00	  4	  7		  0	  0	  0		  0					  0	  0								ID__________________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  4	 28		  0	  0	  0		  0					  0	  0								:		
GV_ID	I	INT4	 10	80	00	80	02	00	  4	 30		  0	  0	  0		  0					  0	  0								__________		
GERI		CHAR	 11	00	00	00	30	00	  4	 83		  0	  0	  0		  9	P				  0	  0	102							@9S@_Geri__	                                                                                                                                                                        &BACK	
AD	0	CHAR	 20	00	00	00	30	00	  5	  7		  0	  0	  0		  0					  0	  0								Ad__________________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  5	 28		  0	  0	  0		  0					  0	  0								:		
GV_AD	C	CHAR	 20	80	00	80	02	00	  5	 30		  0	  0	  0		  0					  0	  0								____________________		
SOYAD	0	CHAR	 20	00	00	00	30	00	  6	  7		  0	  0	  0		  0					  0	  0								Soyad_______________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  6	 28		  0	  0	  0		  0					  0	  0								:		
GV_SOYAD	C	CHAR	 20	80	00	80	02	00	  6	 30		  0	  0	  0		  0					  0	  0								____________________		
CINSIYET	0	CHAR	 20	00	00	00	30	00	  7	  7		  0	  0	  0		  0					  0	  0								Cinsiyet____________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  7	 28		  0	  0	  0		  0					  0	  0								:		
GV_RAD1	C	CHAR	  1	80	00	80	00	00	  7	 30		  0	  0	  0		  0	A				  0	  0	103									
GV_RAD1	0	CHAR	  5	00	00	00	30	00	  7	 32		  0	  0	  0		  0	A				  0	  0	103							Erkek		
GV_RAD2	C	CHAR	  1	80	00	80	00	00	  7	 38		  0	  0	  0		  0	A				  0	  0	103									
GV_RAD2	0	CHAR	  5	00	00	00	30	00	  7	 40		  0	  0	  0		  0	A				  0	  0	103							Kad#n		
DOGUM	0	CHAR	 20	00	00	00	30	00	  8	  7		  0	  0	  0		  0					  0	  0								Do#um_Tarihi________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  8	 28		  0	  0	  0		  0					  0	  0								:		
GV_DOGUM	D	DATS	 10	80	00	80	02	08	  8	 30		  0	  0	  0		  0					  0	  0			SRM_F4_DATUM					__________		
YAS	0	CHAR	  3	00	00	00	30	00	  9	  7		  0	  0	  0		  0					  0	  0								Ya#	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	  9	 28		  0	  0	  0		  0					  0	  0								:		
GV_YAS	I	INT4	 11	80	00	80	00	00	  9	 30		  0	  0	  0		 13					  0	  0								___________	 DL	
SEHIR	0	CHAR	 20	00	00	00	30	00	 10	  7		  0	  0	  0		  0					  0	  0								#ehir_______________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	 10	 28		  0	  0	  0		  0					  0	  0								:		
GV_SEHIR	C	CHAR	 15	80	00	80	02	00	 10	 30		  0	  0	  0		  0					  0	  0								_______________		
TELEFON	0	CHAR	 20	00	00	00	30	00	 11	  7		  0	  0	  0		  0					  0	  0								Telefon_Numaras#____	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	 11	 28		  0	  0	  0		  0					  0	  0								:		
GV_TELEFON	C	CHAR	 20	80	00	80	02	00	 11	 30		  0	  0	  0		  0					  0	  0								____________________		
MAIL	0	CHAR	 20	00	00	00	30	00	 12	  7		  0	  0	  0		  0					  0	  0								Mail_Adresi_________	                                                                                                                                                                                                                                                        X	
	0	CHAR	  1	00	00	00	30	00	 12	 28		  0	  0	  0		  0					  0	  0								:		
GV_MAIL	C	CHAR	 50	80	00	80	02	00	 12	 30		  0	  0	  0		  0					  0	  0								__________________________________________________		
BILGI_GETIR		CHAR	 27	00	00	00	30	00	 14	 26		  0	  0	  0		 25	P				  0	  0	104							@FA@_Bilgileri_Getir_______	                                                                                                                                                                        &SEARCH	
GUNCELLE		CHAR	 27	00	00	00	30	00	 14	 56		  0	  0	  0		 25	P				  0	  0	105							@42@_Bilgileri_Güncelle____	                                                                                                                                                                        &UPDATE	
SIL		CHAR	 27	00	00	00	30	00	 16	 26		  0	  0	  0		 25	P				  0	  0	106							@11@_Çal##an#_Sil__________	                                                                                                                                                                        &DELETE	
BILGI_TEMIZLE		CHAR	 27	00	00	00	30	00	 16	 56		  0	  0	  0		 25	P				  0	  0	107							@0Y@_Bilgileri_Temizle_____	                                                                                                                                                                        &CLEAR	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_0200.																																
																																
PROCESS AFTER INPUT.																																
 MODULE USER_COMMAND_0200.																																
%_PARAMS																																
																																
