****************************************************************																																
*   THIS FILE IS GENERATED BY THE SCREEN PAINTER.              *																																
*   NEVER CHANGE IT MANUALLY, PLEASE !                         *																																
****************************************************************																																
%_DYNPRO																																
Z_KURUMSAL_CALISAN_LISTESI																																
0400																																
752																																
             40																																
%_HEADER																																
Z_KURUMSAL_CALISAN_LISTESI              0400 0400     27202192 37  0  0 29208  0G E                              20240930160917																																
%_DESCRIPTION																																
Çal##anlar Listesi																																
%_FIELDS																																
CALISAN_BILGI		CHAR	199	00	00	08	30	00	  2	  5		  0	  0	  0		 26	R				  0	  0	102							Çal##an_Listesi_Görüntüleme_________________________________________________________________________________________________________		
YENILE		CHAR	 19	00	00	08	30	00	  4	 18		  0	  0	  0		 15	P				  0	  0	103							@42@_YEN#LE________	                                                                                                                                                                        &REFRESH	
EXCEL		CHAR	 37	00	00	00	30	00	  4	 76		  0	  0	  0		 35	P				  0	  0	104							@J3@_Verileri_Excel_Dosyas#na_Aktar__	                                                                                                                                                                        &EXCEL	
GERI		CHAR	 12	00	00	08	30	00	  4	177		  0	  0	  0		 10	P				  0	  0	105							@9S@_GER#___	                                                                                                                                                                        &BACK	
CALISANLAR			145	C4	F0	00	00	00	  8	 16	E	101	  1	  1		 18	T				  5	 15										
ZKURUMSALCALISAN-ID	X	INT4	  9	B0	00	90	30	00	  1	  1	T	101	  1	  1		  9					 10	  0								_________	                                       00	
ZKURUMSALCALISAN-AD	C	CHAR	 20	A0	00	80	30	00	  1	  2	T	101	  1	  1		 20					 40	  0								____________________	                                       00	
ZKURUMSALCALISAN-SOYAD	C	CHAR	 20	A0	00	80	30	00	  1	  3	T	101	  1	  1		 20					 40	  0								____________________	                                       00	
ZKURUMSALCALISAN-SEHIR	C	CHAR	 15	A0	00	80	30	00	  1	  4	T	101	  1	  1		 15					 30	  0								_______________	                                       00	
ZKURUMSALCALISAN-MAIL	C	CHAR	 50	A0	02	80	30	00	  1	  5	T	101	  1	  1		 50					100	  0								__________________________________________________	                                       00	
ZKURUMSALCALISAN-TELEFON	C	CHAR	 20	A0	00	80	30	00	  1	  6	T	101	  1	  1		 20					 40	  0								____________________	                                       00	
ZKURUMSALCALISAN-DOGUM	D	DATS	 10	A0	00	80	30	08	  1	  7	T	101	  1	  1		 10					 16	  0								__________	X                                      00	
ZKURUMSALCALISAN-YAS	X	INT4	  9	B0	00	90	30	00	  1	  8	T	101	  1	  1		  9					 10	  0								_________	                                       00	
ZKURUMSALCALISAN-CINSIYET	C	CHAR	  1	A0	00	80	30	00	  1	  9	T	101	  1	  1		  1					  2	  0								_	                                       00	
P_SEARCH_NAME	C	CHAR	 20	80	00	80	00	00	 14	173		  0	  0	  0		  0					  0	  0								____________________		
CALISAN_ARAMA		CHAR	 19	00	00	00	30	00	 15	175		  0	  0	  0		 16	P				  0	  0	106							@GS@_Çal##an_Ara___	                                                                                                                                                                        &SEARCH	
CALISANLAR_TOP		CHAR	  4	00	00	08	30	00	 26	 16		  0	  0	  0		  3	P				  0	  0	107			PAG				@2Y@	                                                                                                                                                                        CALISANLAR_P--	
CALISANLAR_PREVIOUS		CHAR	  4	00	00	08	30	00	 26	 20		  0	  0	  0		  3	P				  0	  0	108			PAG				@2Z@	                                                                                                                                                                        CALISANLAR_P-	
CALISANLAR_NEXT		CHAR	  4	00	00	08	30	00	 26	 24		  0	  0	  0		  3	P				  0	  0	109			PAG				@30@	                                                                                                                                                                        CALISANLAR_P+	
CALISANLAR_BOTTOM		CHAR	  4	00	00	08	30	00	 26	 28		  0	  0	  0		  3	P				  0	  0	110			PAG				@31@	                                                                                                                                                                        CALISANLAR_P++	
OK_CODE		CHAR	 20	80	10	08	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
*&SPWIZARD: PBO FLOW LOGIC FOR TABLECONTROL 'CALISANLAR'																																
  MODULE CALISANLAR_INIT.																																
*&SPWIZARD: MODULE CALISANLAR_CHANGE_TC_ATTR.																																
*&SPWIZARD: MODULE CALISANLAR_CHANGE_COL_ATTR.																																
  LOOP AT   G_CALISANLAR_ITAB																																
       INTO G_CALISANLAR_WA																																
       WITH CONTROL CALISANLAR																																
       CURSOR CALISANLAR-CURRENT_LINE.																																
*&SPWIZARD:   MODULE CALISANLAR_CHANGE_FIELD_ATTR																																
    MODULE CALISANLAR_MOVE.																																
    MODULE CALISANLAR_GET_LINES.																																
  ENDLOOP.																																
																																
 MODULE STATUS_0400.																																
																																
PROCESS AFTER INPUT.																																
*&SPWIZARD: PAI FLOW LOGIC FOR TABLECONTROL 'CALISANLAR'																																
  LOOP AT G_CALISANLAR_ITAB.																																
    CHAIN.																																
      FIELD ZKURUMSALCALISAN-ID.																																
      FIELD ZKURUMSALCALISAN-AD.																																
      FIELD ZKURUMSALCALISAN-SOYAD.																																
      FIELD ZKURUMSALCALISAN-SEHIR.																																
      FIELD ZKURUMSALCALISAN-MAIL.																																
      FIELD ZKURUMSALCALISAN-TELEFON.																																
      FIELD ZKURUMSALCALISAN-DOGUM.																																
      FIELD ZKURUMSALCALISAN-YAS.																																
      FIELD ZKURUMSALCALISAN-CINSIYET.																																
    ENDCHAIN.																																
  ENDLOOP.																																
  MODULE CALISANLAR_USER_COMMAND.																																
*&SPWIZARD: MODULE CALISANLAR_CHANGE_TC_ATTR.																																
*&SPWIZARD: MODULE CALISANLAR_CHANGE_COL_ATTR.																																
																																
 MODULE USER_COMMAND_0400.																																
%_PARAMS																																
																																
